"""empty message

Revision ID: a544f51d9763
Revises: 
Create Date: 2025-03-05 20:49:58.699038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a544f51d9763'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_cases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='用例唯一ID'),
    sa.Column('env', sa.String(length=50), nullable=False, comment='环境：RC、Stage、Prod'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='模块：stat、user、noah'),
    sa.Column('creator', sa.String(length=50), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('modifier', sa.String(length=50), nullable=False, comment='最后一次修改人'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', name='http_method'), nullable=False, comment='请求方法'),
    sa.Column('url', sa.String(length=255), nullable=False, comment='接口URL'),
    sa.Column('headers', sa.JSON(), nullable=True, comment='请求头（JSON格式）'),
    sa.Column('params', sa.JSON(), nullable=True, comment='请求参数（JSON格式）'),
    sa.Column('expected', sa.JSON(), nullable=False, comment='预期结果（JSON格式）'),
    sa.Column('ignored_fields', sa.JSON(), nullable=True, comment='忽略校验字段（JSON数组）'),
    sa.Column('is_deleted', sa.Boolean(), nullable=True, comment='软删除标记'),
    sa.Column('skip_execution', sa.Boolean(), nullable=True, comment='是否跳过执行'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('username', sa.String(length=40), nullable=False, comment='用户姓名'),
    sa.Column('pwd', sa.String(length=360), nullable=True, comment='密码'),
    sa.Column('salt', sa.String(length=32), nullable=True, comment='salt'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('test_cases')
    op.drop_table('revoked_tokens')
    # ### end Alembic commands ###
